#!/bin/sh
echo "
Telemetry
---------
The Azure Functions Core tools collect usage data in order to help us improve your experience.
The data is anonymous and doesn't include any user specific or personal information. The data is collected by Microsoft.

You can opt-out of telemetry by setting the FUNCTIONS_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.
"